project:
  type: book              # keep book features & numbering
  output-dir: _output       # put everything in one place

  render:
    - index.qmd            
book:
  title: "Final Project Report"  # Change to your title of the project
  subtitle: Sub-title of the Project. # Change to your sub-title of the project
  author: "Name of Student(s)"
  date: May 18, 2025
  reader-mode: true
  page-footer:
    left: |
      Yadav, M., & Sehra, S. S. (2025). 
    right: |
      This book template was built with <a href="https://quarto.org/">Quarto</a>, Courtesy Dr. Sukhjit Singh Sehra.
  # cover-image: cover.jpg
  # favicon: cover.jpg
  site-url: https://sabudh.org/
  repo-url: https://github.com//
  repo-branch: main
  chapters:
    - index.qmd
# Update the following to your references file
bibliography: references.bib

format:
  # ── 1. Multi-page HTML book ──────────────────────────────
  html:
    theme: united
    code-line-numbers: true
    code-link: true
    self-contained: true
    toc: true
    number-sections: true
    # Change the following to your names
    author-meta: "Dr. Sukhjit Singh Sehra"

  # # ── 2. PDF (single file) ─────────────────────────────────
  titlepage-pdf:
    documentclass: book
    classoption: ["oneside", "open=any"]
    number-sections: true
    toc: true
    lof: true
    lot: true
    titlepage: "bg-image"
    titlepage-bg-image: "img/corner-logo.png"
    titlepage-logo: "img/sabudh.png"
    titlepage-header: "The Publisher"
    # Change the following to your names
    titlepage-footer: |
      last name, first name; last name, first name of authors\
    coverpage: "great-wave"
    coverpage-bg-image: "_extensions/nmfs-opensci/titlepage/images/TheGreatWaveoffKanagawa.jpeg"
    coverpage-title: "Sabudh Passion Project"
    coverpage-footer: "Learn and Give Back to Society"
    coverpage-theme:
      page-html-color: "F6D5A8"
      title-fontfamily: "QTDublinIrish.otf"
      title-fontsize: 40
      title-align: "right"
      title-bottom: "10in"
      header-style: "none"
      author-style: "none"
      footer-fontsize: 20
      footer-fontfamily: "QTDublinIrish.otf"
      footer-align: "right"
      footer-bottom: "9.5in"
      date-style: "none"
      bg-image-fading: "north"
    keep-tex: false
    include-in-header:
      text: |
        % delete. this is for the example w CZ diacritics
        \usepackage{babel}  


  # ── 3. EPUB (single file) ────────────────────────────────
  epub:
    cover-image: img/coverpage.png     # optional—remove if you don’t have one
    toc: true
    embed-resources: true

