project:
  type: book              # keep book features & numbering
  output-dir: _book       # put everything in one place

  render:
    - index.qmd            
book:
  title: "Name of Project"
  author: "Name of Student(s)"
  date: May 18, 2025
  reader-mode: true
  page-footer:
    left: |
      Project Name and Author Name(s) 
    right: |
      This book template was built with <a href="https://quarto.org/">Quarto</a>, Courtesy Dr. Sukhjit Singh Sehra.
  # cover-image: cover.jpg
  # favicon: cover.jpg
  site-url: https://sabudh.org/
  repo-url: https://github.com//
  repo-branch: main
  chapters:
    - index.qmd

bibliography: references.bib

format:
  # ── 1. Multi-page HTML book ──────────────────────────────
  html:
    theme: united
    code-line-numbers: true
    code-link: true
    self-contained: true
    toc: true
    number-sections: true
    author-meta: "Dr. Sukhjit Singh Sehra"

  # # ── 2. PDF (single file) ─────────────────────────────────
  pdf:
    documentclass: scrreport
    lof: true
    lot: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
   
  # ── 3. EPUB (single file) ────────────────────────────────
  epub:
    # cover-image: cover.png     # optional—remove if you don’t have one
    toc: true
    embed-resources: true

